import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar';
import ContactForm from './components/ContractForm';
import Footer from './components/Footer';
import { Providers } from './providers';
import { SpeedInsights } from '@vercel/speed-insights/next';
import NavigationEvents from './components/NavigationEvents';
import { Suspense } from 'react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{ background: 'rgb(255, 255, 255)' }}
      >
        <Providers>
          <Suspense fallback={null}>
            <NavigationEvents />
          </Suspense>
          <Navbar />
          <main style={{ marginTop: '85px' }}>{children}</main>
          <ContactForm />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
